apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: new-pipeline
  namespace: demo
spec:
  tasks:
    - name: echo-hello-world
      taskRef:
        kind: Task
        name: echo-hello-world
